# These are supported funding model platforms

github: [rubiin]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a Open collective username
ko_fi: rubiin
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
buy_me_a_coffee: rubiin
thanks_dev: rubiin
